#' refPlausible
#
#' @description refPlausible enables the user to quickly check the reference dataset concerning the expeced ESM time period for each participant.
#
#' @param refDf a data.frame. The reference dataset.
#
#' @param RELEVANTVN_REF a list. This list is generated by function \code{\link{setREF}} and it is extended once either by function \code{\link{genDateTime}} or by function \code{\link{splitDateTime}}.
#
#' @param units a character. This character must be exactly one of the following options: auto, secs, mins, hours, days, weeks. For more information see the R base function \code{\link{difftime}}.
#
#' @details The units of the ESM period can be selected by the user, namely one of the following: auto, secs, mins, hours, days, weeks. For more information enter ?difftime in the R console.
#
#' @return A data.frame, i.e. \code{refDf}. The returned data.frame will have one additional column with the ESM period for each participant. See \strong{Details} for more information.
#
#' @examples
#' # o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o
#' # Prerequisites in order to execute refPlausible. Start ------
#' # Use example list delivered with the package
#' RELEVANTVN_REF <- RELEVANTVN_REFext
#' # Prerequisites in order to execute refPlausible. End --------
#' # ------------------------------------------------------
#' # Run function 8 of 29; see esmprep functions' hierarchy.
#' # ------------------------------------------------------
#' # In an ESM study all participants answer questionnaires during a time period which
#' # usually is equal across all participants (e.g. seven days). This function enables the
#' # user to check whether in the reference dataset the ESM period is plausible. For
#' # instance, a negative ESM time period would clearly be implausible, e.g. the user
#' # setting the beginning of the ESM time period after the end of it (which is
#' # impossible unless a functioning time machine is involved :-) ).
#' referenceDfNew1 <- refPlausible(refDf=referenceDfNew, units="days", RELEVANTVN_REF)
#' # o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o=o
#
#' @seealso Exemplary code (fully executable) in the documentation of \code{\link{esmprep}} (function 8 of 29).
#
#' @export
#
refPlausible <- function(refDf=NULL, units="days", RELEVANTVN_REF) {
	
	if(!is.data.frame(refDf)) {
		stop("Argument 'refDf' must be of class data.frame.")
	}
	
	if(!is.character(units)) {
		stop("Argument 'units' must be of class character.")
	}
	
	if(!any(c("auto", "secs", "mins", "hours", "days", "weeks") %in% units)) {
		stop("Argument 'units' received an invalid value, please select exactly one of the following options: 'auto', 'secs', 'mins', 'hours', 'days', 'weeks'. For details enter '?difftime' in the R console.")
	}
	
	# Error handling function for all set-up lists generated by setES and setREF.
    # Both lists RELEVANTVN_ES and RELEVANTVN_REF get extended either by function
    # genDateTime or by function splitDateTime!
    SETUPLISTCheck(RELEVANTINFO_ES=NULL,
    			   RELEVANTVN_ES=NULL,
    			   RELEVANTVN_REF=RELEVANTVN_REF)
	
	timeDiffDays <- base::difftime(refDf[,RELEVANTVN_REF[["REF_END_DATETIME"]]],
						 refDf[,RELEVANTVN_REF[["REF_START_DATETIME"]]],
						 units=units)
	
	refDf[,paste0("ESMperiod", toupper(units))] <- as.numeric(timeDiffDays)
	return(refDf)
	
}
