#' Resulting list after function genDateTime has been executed on the list of ESM datasets.
#'
#' \strong{Note}: The extended (see ending 'ext') list \code{RELEVANTVN_ESext} is the result of the function \code{\link{genDateTime}}, when the list of datasets \code{keyLs} is one of the function arguments. The list \code{RELEVANTVN_ES} (before being extended) is generated by the function \code{\link{setES}}.
#'
#' @docType data
# @keywords datasets
# @name RELEVANTVN_ESext
#
# @source R package esmprep.
"RELEVANTVN_ESext"