#' Resulting list after function genDateTime has been executed on the reference dataset.
#'
#' \strong{Note}: The extended (see ending 'ext') list \code{RELEVANTVN_REFext} is the result of the function \code{\link{genDateTime}}, when the reference dataset \code{\link{referenceDf}} is one of the function arguments. The list \code{RELEVANTVN_REF} (before being extended) is generated by the function \code{\link{setREF}}.
#'
#' @docType data
# @keywords datasets
# @name RELEVANTVN_REFext
#
# @source R package esmprep.
"RELEVANTVN_REFext"